language: node_js
node_js:
- '7'

deploy:
  provider: heroku
  app: fast-crag-46725
  api_key:
    secure: fR1TKaz2XK3wAGTS2+kNVI6JUOzaLU7fFRo1p4HhYBe0gmwJF8Ylv4IyknDp87kGTuCXk3qKEl3szMizdlrzsjeQs/Yho/W6dS1uc9gKHUdGI6Ndko0hL5Cg/2dzG7hzrXoh4bRgZZJQbFSKM9Z8dIVwiPQEolbo796pJSdlvtKN4Z52Y+nKVCLY584D4ARrnhh8RYENWtnFfYwVGyWyfB6Ze1eppu10T49yRx6ehn0EbsOSOLg+wO7m0hHuB/RIx7Iu1pe94MnVwFF9iAbRy1oFrkuaJqP6R3eI7W7bWxh/A2cBIIhQHvbyBS6kidufSIZhh7PpCSPG4fVShNI14r+pNg3IkunZG4QfKoOCZqPxYeEHgrO5K1jTQb4/9t2hcWPdr7zMVs/QbjzyO5Dmc0BJue8BHYp2aHe1MYEAz6oTcEIe/ba4+SGpnqZ+uROd5z7yFmlxFVy3U1rtUtcFvCPY2qWy5sAfpZ2nBEVOrwyFQyC/kv4VreY//NEPw8PfIYiUoY2/awB2xjvzhD1Q8hMioWiE9rTyrqGPJjLuVB3Jm8hPUpzD7/rvKOasYbRQEqS7EXIBSn/nPaBrp+KGs7YhE/PGb4F0ta4aE0QjSlSS4oyocwCYrt2tFpEu1Yz60mf8ctLgOmf3OmgUjkEicBTw8xVECnsCSHLoZJneb/8=
